name: CI Tests

on:
  push:
    branches: ["*"]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install fastapi uvicorn pytest

      - name: Run tests
        run: pytest code/tests/ --collect-only -v

      - name: Build artifact
        run: |
          mkdir -p build/
          cp -r code/ build/code/
          echo "Automated Payroll System Build - $GITHUB_SHA" > build/version.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: payroll-build
          path: build/

